name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest
    env:
      working-directory: ./Docs

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Test
        run: ls -R
        working-directory: ${{ env.working-directory }}

      - name: Install
        run: bundle install
        working-directory: ${{ env.working-directory }}

      - name: Deploy
        run: bash tools/deploy.sh
        working-directory: ${{ env.working-directory }}
